FROM tensorflow/tensorflow:latest-gpu-py3
LABEL author="Joe Barbere"

# set timezone
RUN echo 'Etc/UTC' > /etc/timezone \
	&& ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime

RUN apt update && apt install -y \
	dirmngr \
	wget \
	tzdata \
	&& rm -rf /var/lib/apt/lists/*

# adding keys for ROS
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -

# installing ros
RUN apt update && apt install -y \
	python-rosinstall \
	python3-colcon-common-extensions \
	python3-pip \
	ros-melodic-desktop-full \
	ros-melodic-effort-controllers \
	#ros-melodic-ros-controllers \
	#ros-melodic-ros-control \
	#ros-melodic-teleop-twist-keyboard \
	&& rm -rf /var/lib/apt/lists/*

# installing additional stuff
RUN apt update && apt install -y \
	curl \
	mlocate \
	tmux \
	htop \
	git \
	nano \
	&& rm -rf /var/lib/apt/lists/*

# update ROS dependencies
RUN rosdep init && rosdep update

# installing colcon bundle tools
RUN pip3 install -U setuptools && pip3 install colcon-ros-bundle

# match robomaker dir structure
RUN mkdir -p /home/ubuntu/catkin_ws/src

# create central dir for mapping data back to the host
RUN mkdir /data

# install minio
RUN wget https://dl.min.io/server/minio/release/linux-amd64/minio
RUN sudo chmod +x minio
RUN sudo mv minio /usr/local/bin
RUN sudo useradd -r minio-user -s /sbin/nologin
RUN sudo chown minio-user:minio-user /usr/local/bin/minio

# install ELK
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
RUN echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
RUN sudo apt-get update
RUN sudo apt-get install -y default-jdk
RUN sudo apt-get install -y elasticsearch logstash kibana && rm -rf /var/lib/apt/lists/*

# install additional useful python packages
RUN pip3 install elasticsearch python-logstash jupyter tornado && pip3 install jupyter-tensorboard

# install cuda/cudnn
COPY cuda_9.0.176_384.81_linux.run /tmp
COPY cudnn-9.0-linux-x64-v7.6.5.32.tgz /tmp

WORKDIR /tmp

RUN chmod +x cuda_9.0.176_384.81_linux.run
RUN ./cuda_9.0.176_384.81_linux.run --silent --toolkit --override

RUN touch ~/.bashrc
RUN echo 'export PATH=/usr/local/cuda-9.0/bin:$PATH' >> ~/.bashrc \
  && echo 'export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc \
  && echo 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc \
  && . ~/.bashrc

RUN tar -xzvf cudnn-9.0-linux-x64-v7.6.5.32.tgz

RUN cp -P cuda/include/cudnn.h /usr/local/cuda-9.0/include
RUN cp -P cuda/lib64/libcudnn* /usr/local/cuda-9.0/lib64/
RUN chmod a+r /usr/local/cuda-9.0/lib64/libcudnn*